security:
   # encoder
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12

    
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        
    firewalls:
        main:
            pattern:   ^/
            # access_denied_handler: App\Security\AccessDeniedHandler
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            # guard:
            #     authenticators:
            #         - App\Security\LoginAuthenticator
            
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/member, roles: ROLE_USER }
